name: 'jaffle_shop'

config-version: 2
version: '0.1.0'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=0.0.1", "<2.0.0"]

seeds:
  jaffle_shop:
    employee:
      enabled: true
      all_varchar: true  # Force all columns to load as VARCHAR
    employee2service:
      enabled: true

models:
  jaffle_shop:
    materialized: table  # Default materialization for all models in jaffle_shop
    staging:
      materialized: view
      stg_products:
        materialized: table  # Explicitly materialize stg_products as a table
      +docs:
        node_color: 'silver'
    mart:
      materialized: table  # Materialize all mart models as tables
      +docs:
        node_color: 'gold'
