name: 'beauty_salon'

config-version: 2
version: '0.1.0'

profile: 'beauty_salon'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=0.0.1", "<2.0.0"]

seeds:
  +docs:
    node_color: '#cd7f32'

models:
  beauty_salon:
    materialized: table
    staging:
      materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'

