version: 2

models:
  - name: stg_customer
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_appointment
    columns:
      - name: appointment_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['arranged', 'done', 'cancelled']

  - name: stg_payment
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['online', 'salon cash', 'salon card', 'na']
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_service
    columns:
      - name: id
        tests:
          - unique
          - not_null
